server:
  port: 9101

#dubbo配置
dubbo:
  application:
    name: manager
  registry:
    protocol: zookeeper
    address: 192.168.111.129:2181
  protocol:
    name: dubbo
    port: 20882

#ossclient配置
oss:
  endpoint: wwww.baidu.com
  accessKeyId: access key id
  secretAccessKey: secret access key