#spring配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.111.129:3306/xshop_goods?characterEncoding=UTF8
    username: root
    password: root
    dbcp2:
      min-size: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

#dubbo配置
dubbo:
  application:
    name: goods
  registry:
    protocol: zookeeper
    address: 192.168.111.129:2181
  protocol:
    name: dubbo
    port: 20881
  monitor:
    protocol: registry

#雪花算法
idWork:
  datacenterId: 1
  workerId: 1